config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'pages#home'
  resources :monsters
  resources :teams

  namespace :api do
    api version: 1, allow_prefix: 'v' do
      scope module: 'v1' do
        resources :monsters
        resources :teams do
          member do
            get :monsters
            post :add_monster
          end
        end
      end
    end
  end

end

app/models/monster.rb
class Monster < ActiveRecord::Base
  validates :name, presence: true
  validates :power, presence: true
  validates :monster_type, presence: true
  validates_inclusion_of :monster_type, in: %w(fire water earth electric wind)
  validates :user_id, presence: true
  validate :group_count

  belongs_to :user
  has_many :monsters_to_teams, dependent: :destroy
  has_many :teams, through: :monsters_to_teams

  def group_count
   errors.add(:base, "You can only have a maximum of 20 monsters") if user.monsters.count == 20
  end

  TYPES = %w(fire water earth electric wind)

  RULES = {
    :fire     => {:fire => :fire, :water => :fire, :earth => :fire, :electric => :fire, :wind => :fire},
    :water    => {:fire => :water, :water => :water, :earth => :earth, :electric => :electric, :wind => :wind},
    :earth => {:fire => :earth, :water => :earth, :earth => :earth, :electric => :electric, :wind => :wind},
    :electric => {:fire => :electric, :water => :electric, :earth => :electric, :electric => :electric, :wind => :wind},
    :wind => {:fire => :wind, :water => :wind, :earth => :wind, :electric => :wind, :wind => :wind}
  }

end

app/models/monsters_to_team.rb
class MonstersToTeam < ActiveRecord::Base
  belongs_to :monster
  belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :user
  has_many :monsters_to_teams, dependent: :destroy
  has_many :monsters, through: :monsters_to_teams
  validate :group_count

  def group_count
    errors.add(:base, "You can only have a maximum of 3 teams") if user.teams.count == 3
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :validatable, :token_authenticatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :monsters, dependent: :destroy
  has_many :teams, dependent: :destroy
  

  def self.find_or_create_by_auth(auth_data)
    user = self.find_or_create_by(uid: auth_data["uid"])
    if user.email != auth_data.extra.raw_info.email
      user.email = auth_data.extra.raw_info.email
      user.name = auth_data.extra.raw_info.name
      user.password = Devise.friendly_token[0,20]
      user.save
    end
    return user
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < RocketPants::Base
  include Devise::Controllers::Helpers
  before_filter :authenticate_user!
  version 1
end

app/controllers/api/v1/monsters_controller.rb
class Api::V1::MonstersController < Api::V1::BaseController  
  before_action :set_monsters, only: [:index, :create]
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  def index
    dir = params[:dir] || "asc"
    @monsters = case params[:order]
    when nil
       @monsters
    when "weakness"
      @monsters.sort do |a, b|
        winner = winner(a.monster_type, b.monster_type)
        case
        when a.monster_type.to_sym == winner
          dir == "asc" ? 1 : -1
        when b.monster_type.to_sym == winner
          dir == "asc" ? -1 : 1
        end
      end
    else
      @monsters.order("#{params[:order]} #{dir}")
    end

    expose @monsters
  end

  def show
    expose @monster
  end
  
  def create
    expose @monsters.create(monster_params), status: :created
  end

  def update
    expose @monster.update_attributes(monster_params)
  end

  def destroy
    expose @monster.destroy
  end
  
  private

  def set_monsters
    @monsters = current_user.monsters
  end

  def set_monster
    @monster = Monster.find(params[:id])
  end

  def winner(p1, p2)
    Monster::RULES[p1.to_sym][p2.to_sym]
  end

  def monster_params
    params.require(:monster).permit(:name, :power, :monster_type)
  end
end

app/controllers/api/v1/teams_controller.rb
class Api::V1::TeamsController < Api::V1::BaseController 
  before_action :set_teams, only: [:index, :create]
  before_action :set_team, only: [:show, :edit, :update, :destroy, :monsters, :add_monster]

  def index
    expose @teams
  end

  def show
    expose @team
  end
  
  def create
    expose @teams.create(team_params), status: :created
  end

  def update
    expose @team.update_attributes(team_params)
  end

  def destroy
    expose @team.destroy
  end

  def monsters
    expose @team.monsters
  end

  def add_monster
    monster = Monster.find(team_params[:monster_id])
    @team.monsters << monster
    expose @team.monsters
  end

  
  private

  def set_teams
    @teams = current_user.teams
  end

  def set_team
    @team = Team.find(params[:id])
  end

  def team_params
    params.require(:team).permit(:name, :monster_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]
  before_action :set_teams, only: [:new, :edit]

  def index
    @monsters = current_user.monsters.all
  end

  def show
  end

  def new
    @monster = current_user.monsters.new
  end

  def edit
  end

  def create
    @monster = current_user.monsters.new(monster_params)
    if @monster.save
      redirect_to @monster, notice: 'Monster was successfully created.'
    else
      render :new
    end
  end

  def update
    if @monster.update(monster_params)
      redirect_to @monster, notice: 'Monster was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @monster.destroy
    redirect_to monsters_url, notice: 'Monster was successfully destroyed.'
  end

  private
    def set_monster
      @monster = Monster.find(params[:id])
    end

    def set_teams
      @teams = current_user.teams
    end

    def monster_params
      params.require(:monster).permit(:name, :power, :monster_type, team_ids: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  def index
    @teams = current_user.teams.all
  end

  def show
  end

  def new
    @team = current_user.teams.new
  end

  def edit
  end

  def create
    @team = current_user.teams.new(team_params)
    if @team.save
      redirect_to @team, notice: 'Team was successfully created.'
    else
      render :new
    end
  end


  def update
    if @team.update(team_params)
      redirect_to @team, notice: 'Team was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @team.destroy
    redirect_to teams_url, notice: 'Team was successfully destroyed.'
  end

  private
    def set_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.require(:team).permit(:name, :monster_id)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_or_create_by_auth(request.env["omniauth.auth"])
    sign_in_and_redirect user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MonsterApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <%= link_to "Home", root_path%>
<% end %>
  <%= yield %>

</body>
</html>

app/views/monsters/_form.html.erb
<%= form_for(@monster) do |f| %>
  <% if @monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% @monster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :power %>
    <%= f.text_field :power %>
    <%= f.label :monster_type %>
    <%= f.select :monster_type, options_for_select(Monster::TYPES.to_a) %>
    <%= f.label :team %>
    <%= select_tag "monster[team_ids]", options_from_collection_for_select(@teams, 'id', 'name', @monster.teams.map{|t| t.id}), { :multiple => true, :size => 6 } %>
    <%= f.submit %>
  </div>
<% end %>

app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form' %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Monsters</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.name %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monster', new_monster_path %>

app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form' %>

<%= link_to 'Back', monsters_path %>

app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>
<p>Name: <%= @monster.name %></p>
<p>Power: <%= @monster.power %></p>
<p>Type: <%= @monster.monster_type %></p>
<p>Teams: <%= @monster.teams.pluck(:name).join(', ')  if @monster.teams.present? %></p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>

app/views/pages/home.html.erb
<% if current_user.nil? %>
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% else %>
  <p><%= current_user.name %></p>
  <p><%= link_to "Monsters", monsters_path %></p>
  <p><%= link_to "Teams", teams_path %></p>
<% end %>